# https://github.com/marketplace/actions/release-drafter#configuration
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

# https://github.com/release-drafter/release-drafter#version-resolver
#   With the version-resolver option version number incrementing can be
#   resolved automatically based on labels of individual pull requests.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

# https://github.com/release-drafter/release-drafter#version-resolver
#   With the categories option you can categorize pull requests in release
#   notes using labels.
categories:
  - title: '💥 Breaking changes'
    labels:
      - 'breaking-change'
  - title: '🚀 Features'
    labels:
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
  - title: '🧪 Testing'
    labels:
      - 'test'
  - title: '📝 Documentation'
    labels:
      - 'docs'
  - title: '🧹 Others'
    labels:
      - 'ci'
      - 'build'
      - 'perf'
      - 'refactor'
      - 'revert'
      - 'style'

# https://github.com/release-drafter/release-drafter#autolabeler
#   You can add automatically a label into a pull request, with the autolabeler
#   option. Available matchers are files (glob), branch (regex), title (regex)
#   and body (regex). Matchers are evaluated independently; the label will be
#   set if at least one of the matchers meets the criteria.
autolabeler:
  - label: 'breaking-change'
    title:
      - '/^\S+!{1}:{1}\s/i'
  - label: 'build'
    title:
      - '/^build/i'
  - label: 'chore'
    title:
      - '/^chore/i'
  - label: 'ci'
    title:
      - '/^ci/i'
  - label: 'docs'
    title:
      - '/^docs/i'
  - label: 'feat'
    title:
      - '/^feat/i'
  - label: 'fix'
    title:
      - '/^fix/i'
  - label: 'perf'
    title:
      - '/^perf/i'
  - label: 'refactor'
    title:
      - '/^refactor/i'
  - label: 'revert'
    title:
      - '/^revert/i'
  - label: 'style'
    title:
      - '/^style/i'
  - label: 'test'
    title:
      - '/^test/i'


template: |
  ## What’s Changed

  $CHANGES
